config/routes.rb
          get "verify_coupon"
        end
      end
      resources :tables, only: [:index,:update] do
        collection do
          post "swap_table"
        end
      end
      resources :orders, only: [:index, :create, :update, :show] do
        collection do
          post "cancel_item"
          post "verify_deliverable_otp"
          post "resend_deliverable_otp"
        end
      end

      resources :external_orders, only: [:index, :create, :update] do
        collection do
          post "set_status"
        end
      end
      resources :thirdparty_callbacks, only: [:create, :show] do
        collection do
          
        end
      end
      resources :resource_order_histories, only: [:index, :create, :show]
      resources :zomato_external_orders, only: [:create]
      resources :bills, only: [:index, :show, :create, :update] do
        collection do
          get "find_bill_by_serial"
          put "bill_on_hold"
        end
      end  
      
      resources :customer_states,only:[:index] do
      end

      resources :tags, only: [:index] do
      end
      resources :customer_state_transitions, only: [:index,:create,:show] do
      end
      resources :settlements, only: [:create]
      resources :customers, only: [:show, :create, :update] do
        collection do
          post "login"
          post "find_by_login"
          post "add_address"
          get "forgot_password"
          put "reset_password"
          post "search_by_customer_name"
          post "login_by_otp"
          post "verify_otp"
          post "add_financial_account"
          get "account_transaction_history"
        end
        member do
          put "change_password"
        end  
      end

      resources :approvals do
        collection do
          post "update_approval"
        end
      end

      resources :own_customers, only: [:create, :update] do
        collection do
          get "find_by_identifications"
          post "customer_queues"
          get "queue_index"
          put "update_customer_queues"
        end
      end 
      resources :customer_queues, only: [:index, :create, :update, :show]
      resources :users, only: [:index,:show,:destroy] do
        collection do
          post "login"
          post "logout"
          post "verify_license"
          post "create_live_map_points"
          get  "get_user_incentive"
          get "user_group_data"
          get "get_users_by_role"
        end
      end
      resources :lots, only: [:index, :show] do
        collection do
          get "download_lots"
        end  
      end  
      resources :vendors, only: [:index, :show, :create, :update] do
        collection do
          get 'vendor_pjp'
          post 'allocate_vendor_products'
          post 'vendor_contract_details'
        end
      end
      resources :loyalty_purchases, only: [:create]
      resources :loyalty_cards, only: [:show] do
        collection do
          get :find_by_mobile_no
        end  
      end  
      resources :stocks, only: [:index] do
        collection do
          get :get_all_product_stocks
          get :get_business_type
          get :in_out_stock
        end  
      end  
      resources :stock_transfers, only: [:index, :update, :create] do
        collection do
          post :get_est_price
        end  
      end
      resources :store_requisitions, only: [:create] do
        collection do
          get :get_requistion_deta
          get :received_requisition
          get :send_requisition_log
          put :update_requisition_state
          get :summary_requisition
          get :get_summary_details
          post :create_send
        end
      end

      resources :purchase_orders, only: [:index, :create, :show] do
        collection do
          get :approval_show
        end
      end
      
      resources :vehicles, only: [:index] do
        collection do
          get :get_pickup_packages
          put :update_shipment_status
        end 
      end 
      resources :order_details, only: [:update]
      resources :stock_purchases, only: [:index, :update] do
        collection do
          get :get_payment_details
          get :generate_stock_receive_row
        end  
      end  
      resources :stock_audits, only: [:index, :update]

      resources :reports, only: [:get_dashboard_data] do
        collection do
          get :get_dashboard_data
          get :get_bill_report
          get :get_item_report
          get :get_product_sales
          get :get_bill_details
        end
      end
      resources :denominations, only: [:index]
      
      resources :cash_handlings, only: [:index, :show] do
          collection do 
            post "cash_in"
            post "cash_out"
          end
      end
      resources :resources, only: [:index, :update] do
        collection do
          get :get_available_resource
          post :swap_resource
          get :resource_pjp
          get :by_unique_identity_no
          get :resource_group_data
        end  
      end  
      resources :slots, only: [:index] do
        collection do
          get :get_available_slot
          get :get_resource_slot
          get :get_available_order_slot
        end  
      end  
      resources :stock_predictions do
        collection do
          get :get_stocks_transfer_details
          get :get_product_composition
        end  
      end 
      resources :reservations, only: [:index, :create, :update, :show] do
        collection do
          put "cancel_reservation"
          put "swap_reservation"
        end  
      end  
      resources :resource_types, only: [:index]
      resources :resource_states, only: [:index]
      resources :advertisements, only: [:index]
      resources :news_events, only: [:index]
      resources :feedbacks, only: [:index]
      resources :products, only: [:index,:show] do
        collection do
          get :get_colors_sizes
        end  
      end  
      resources :otps, only: [:create, :update] do
        collection do
          put "resend"
        end
      end
      resources :parties
      resources :guests
      resources :preauths, only: [:create] do
        collection do
          get "check_availability"
        end  
      end  
      resources :paypals do
        collection do
          get "client_token"
          post "checkout"
        end  
      end  
      resources :sale_rules, only: [:index]
      resources :customer_feedbacks, only: [:create] 
      resources :production_processes, only: [:index]
      resources :stock_productions, only: [:create] do
        collection do
          get 'get_products'
        end
        member do 
          get 'show'
        end
      end
      resources :payment_wallets, only: [:index]
      resources :stores do
        collection do
          get 'find_by_pincode'
          get 'store_products'
        end 
      end
      resources :colors, only: [:index]
      resources :sizes, only: [:index]
      resources :inspections, only: [:create,:show]
      post 'wallets/:identity', to: 'wallets#credit'
      get 'wallets/:identity', to: 'wallets#show'
      resources :knowlarities, only: [:index] do
        collection do 
          post 'knowlarity_call_log'
          get 'fetch_current_knowlarity_customer'
        end
      end
      resources :urbanpipers do
        collection do
          post "customer_register"
          get "customer_search"
          put "customer_profile_update"
          post "wallet_transaction"
          post "processing_purchase"
          get "reward_redemption"
        end
      end
      
    end
  end

  resources :dashboards, only: [:index] do
    collection do
      get :sales
      get :inventory
      get :analytics
    end
  end
  resources :loyalty_card_payments
  resources :loyalty_purchases
  resources :loyalty_card_classes
  resources :loyalty_card_transactions
  resources :loyalty_cards
  resources :rooms
  resources :third_party_payment_options
  resources :alpha_promotions
  resources :product_basic_units
  resources :pos_terminals do
    collection do
      get :tally_exporter
      get :page
      get :file
    end
    member do
      get :find_product
      get :find_barcode
    end
  end

  resources :return_items, only: [:create] do
    collection do
      post 'add_item_to_stock', to: "return_items#add_item_to_stock", as: "add_to_stock"
      get 'show_stores', to: "return_items#show_stores", as: "show_stores"
      post 'add_return_item_to_stock', to: "return_items#add_return_item_to_stock", as: "add_return_item_to_stock"
    end
  end

  resources :advertisements do
    resources :advertisement_galleries
    collection do
      post :remove_pic
    end
  end
  resources :denominations, only: [:index]
  
  resources :cash_handlings, only: [:index, :show] do
    collection do 
      post "cash_in"
      post "cash_out"
    end
  end

  post   'delivery_boy_login'   => 'sessions#create'
  resources :delivery_boys do
    member do
      get :assign_unit
      post :create_assign_unit

    end
    collection do
      post :sign_in
      get :assign_order
      get :assign_return
      post "create_assign_order", to: "delivery_boys#create_assign_order"
      post "create_assign_return", to: "delivery_boys#create_assign_return"
      post "cancel_assigned_order/:data", to: "delivery_boys#cancel_assigned_order"
      get :fetch_order_data
      post "cancel_assigned_return"
    end
  end

  resources :notifications do
    collection do
      get :stock_expiry_alerts
      get :thresh_hold_alerts
      get :approval_alerts
    end
  end
  resources :table_reservations,except: [:show] do
    collection do
      get "get_tables_list/:section_id", to: "table_reservations#get_tables_list"
      post "meta_data_cust/:reservation_id", to: "table_reservations#meta_data_create_cust_view"
      post "meta_data_table", to: "table_reservations#meta_data_create_table_view"

app/controllers/api/v2/stores_controller.rb
module Api
  module V2
    class StoresController < ApplicationController

    	### => API Documentation (APIPIE) for 'index' action
      api :GET, '/api/v2/stores', "List of stores of an unit. (Authorization header required for authentication)"
      param :email, String, :required => true, :desc => "Email ID of user, who is sending the request."
      param :device_id, String, :required => true, :desc => "ID of registered device (If its a request from portal send YOTTO05 instead)."
      param :unit_id, String, :required => true, :desc => "Stores of this unit"
    	param :store_type, String, :required => false, :desc => "Type of the store"
    	param :count, String, :required => false, :desc => "If `page` parameter is present in request, this API will response with pagination and by default it will return 20 results. If you want to define the number of results per page, you can do so by adding `count` parameter in your request.", :meta => "`count` parameter is dependent on `page` parameter"
    	param :page, String, :required => false, :desc => "If `page` parameter is present in request, this API will response with pagination and by default it will return 20 results"

    	### => 'index' API Defination
      def index
        @unit = Unit.find(params[:unit_id])
        _per = params[:count] || 20

         store_ids = []
        @unit.stores.map { |e| store_ids.push e.id } if @unit.present?
        @unit.parent_unit.stores.map { |e| store_ids.push e.id } if @unit.parent_unit.present?
        @stores = Store.set_id_in(store_ids)
        @stores = @stores.by_store_type(params[:store_type]) if params[:store_type].present?
        @stores_count = @stores.count
        @stores = @stores.page(params[:page]).per(_per) if params[:page].present?

        rescue Exception => @error
        @log = Rscratch::Exception.log(@error,request) if @error.present? # Log exception
      end

      ### => API Documentation (APIPIE) for 'get_store_details' action
      api :GET, '/api/v2/stores/find_by_pincode', "Store by pincode. (Authorization header required for authentication)"
      param :email, String, :required => true, :desc => "Email ID of user, who is sending the request."
      param :device_id, String, :required => true, :desc => "ID of registered device (If its a request from portal send YOTTO05 instead)."
      param :pincode, String, :required => true

      def find_by_pincode
        @store_details = Store.find_by_pincode(params[:pincode])
        rescue Exception => @error
        @log = Rscratch::Exception.log(@error,request) if @error.present? # Log exception
      end

      ### => API Documentation (APIPIE) for 'create' action
      api :POST, '/api/v2/stores', "Register new store."
      param :email, String, :required => false, :desc => "Email ID of user, who is registering the user."
      param :device_id, String, :required => false, :desc => "ID of registered device (If its a request from portal send YOTTO05 instead)."
      param :store, Hash, :required => true, :desc => <<-EOS

        ==== A sample parameter value is given below
          {
            "name": "Store1 test1",
            "contact_number": "9009009001",
            "address": "West Bengal",
            "pincode": "700102",
            "store_type": "physical_store",
            "unit_id": "7",
            "store_priority": "primary_store",
            "tin_no": "101",
            "tan_no": "102",
            "latitude": "22.100",
            "longitude": "88.010",
            "gstn_no": "201",
            "pan_no": "202",
            "contact_person": "Pravin Kumar1",
            "user_id": "1"
            }
        EOS
      formats ['json']

      def create
        @store = Store.find_by_contact_number(params[:store][:contact_number])
        if @store.present?
          @status_code = 406
          @status_message = "Store exist with this contact no."
        else
          @store = Store.new(params[:store])
          if @store.save
            @store.reload
          else
            @validation_errors = error_messages_for(@store)
          end
        end
        rescue Exception => @error
        @log = Rscratch::Exception.log(@error,request) if @error.present? # Log exception
      end

      api :GET, '/api/v2/stores/store_products', "Store by pincode."
      param :email, String, :required => true, :desc => "Email ID of user, who is sending the request."
      param :device_id, String, :required => true, :desc => "ID of registered device (If its a request from portal send YOTTO05 instead)."
      param :unit_id, String, :required => true, :desc => "Store products of this unit"
      param :count, String, :required => false, :desc => "If `page` parameter is present in request, this API will response with pagination and by default it will return 20 results. If you want to define the number of results per page, you can do so by adding `count` parameter in your request.", :meta => "`count` parameter is dependent on `page` parameter"
      param :page, String, :required => false, :desc => "If `page` parameter is present in request, this API will response with pagination and by default it will return 20 results"

      def store_products
        store_array = []
        _per = params[:count] || 20
        _unit = Unit.find(params[:unit_id])
        @unit_stores = _unit.stores.order("id asc")
        @unit_stores.map { |e| store_array.push e.id}
        @store_products = StoreProduct.order('id desc')
        @store_products = @store_products.set_store_in(store_array)
        @store_products_count = @store_products.count
        @store_products = @store_products.page(params[:page]).per(_per) if params[:page].present?

        rescue Exception => @error
        @log = Rscratch::Exception.log(@error,request) if @error.present? # Log exception
      end

    end
  end
end

app/views/stores/_form.html.haml
- manual_load_javascript "templates/users/get_users_by_role"
= form_for @store, :html => { :class => 'form-horizontal'} do |f|
  - if @store.errors.any?
    #error_explanation
      %h2= "#{pluralize(@store.errors.count, "error")} prohibited this store from being saved:"
      %ul
        - @store.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :store_type, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.select :store_type, options_for_select({"Physical Store" => "physical_store","Virtual Store" => "virtual_store","Production center" => "kitchen_store","Return Store" => "return_store", "Waste Bin" => "waste_bin" },@store.store_type), { include_blank: "Select store type"}, {:class => "form-control"}
  .form-group
    = f.label :store_priority, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.select :store_priority, options_for_select({"Primary Store" => "primary_store","Secondary Store" => "secondary_store"},@store.store_priority), { include_blank: "Select store priority"}, {:class => "form-control"}      
  .form-group
    = f.label :address, :class => 'col-sm-2 control-label'
    .col-sm-4  
      = f.text_area :address, :class => 'form-control', :rows => "4"
  .form-group
    = f.label :pincode, :class => 'col-sm-2 control-label'
    .col-sm-4  
      = f.text_field :pincode, :class => 'form-control'
  .form-group
    = f.label :contact_number, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :contact_number, :class => 'form-control'
  .form-group
    = f.label :tin_no, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :tin_no, :class => 'form-control' 
  .form-group
    = f.label :tan_no, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :tan_no, :class => 'form-control'       
  .form-group
    = f.label :store_image, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.file_field :store_image, :class => 'form-control'
  .form-group
    = f.label :latitude, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :latitude, :class => 'form-control'
  .form-group
    = f.label :longitude, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :longitude, :class => 'form-control'
  .form-group
    = f.label :gstn_no, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :gstn_no, :class => 'form-control'
  .form-group
    = f.label :pan_no, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :pan_no, :class => 'form-control'
  .form-group
    = f.label :contact_person, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :contact_person, :class => 'form-control'
  .form-group
    = f.label "select role", :class => 'col-sm-2 control-label'
    .col-sm-4
      = select_tag "store_user_role", options_for_select(@child_roles.map{ |role| [role.name.humanize, role.id] }), { prompt: "Select role", class: "form-control"}
  .form-group
    = f.label "select user", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.select :user_id, options_for_select(@users.map{ |user| [user.profile.full_name, user.id] }, @store.user_id), { include_blank: "Select user"}, {:class => "form-control"}
  .form-group    
    .col-sm-offset-2.col-sm-10
      = f.submit "#{t :btn_next_step}", :class => 'm-btn blue'

app/views/stores/_kitchen_production_audit_smartlist.html.haml
- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %th.col-md-8{:colspan => 3}
        = smart_listing.sortable "Audit details", "id" 
      %th.col-md-2= smart_listing.sortable "Date", "created_at"
      %th.col-md-2 Action
    %tbody
      - smart_listing.collection.each do |object|
        - _kitchen_pro = KitchenProductionAudit.where(:audit_id => object.audit_id).first
        %tr
          %td.text-center{:style => "width: 1%;", :class=>"#{production_audit_status_class(_kitchen_pro.status)}"}
          %td.fixed-width-xss
            %i.fa.fa-cutlery.fa-2x.padding-5
          %td
            %h5
              ="##{object.audit_id}"                 
              = production_audit_status_tag(_kitchen_pro.status)
            %p.module_description
              %b Audit date:
              =_kitchen_pro.created_at
              
          %td.font-sz-12=#object.created_at.strftime("%d %b %Y, %I:%M %p")  
          %td.col-lg-2.col-xs-3.padding-top-20
            %a.btn.btn-default.btn-sm.btn-social{:href=>"kitchen_production_audits/serial/#{object.audit_id}"} 
              %i.fa.fa-list-ul
              More details
      
  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
- else
  .alert.alert-warning
    No production records found!

app/views/stores/_requisition_sent_smartlist.html.haml
- unless smart_listing.empty?
  %table.data-table
    %thead
      %tr.data-table__selectable-row
        %th
          = smart_listing.sortable "Requisition details", "id" 
        %th  
          = smart_listing.sortable "Status", "status"           
        %th= smart_listing.sortable "Date", "created_at"
        %th.col-lg-3
    %tbody
      - smart_listing.collection.each do |object|
        - _req_transfers = object.stock_transfers
        %tr.data-table__selectable-row
          %td
            %h5
              ="ID: #{object.id} | #{object.store_requisition.name}"                 
            %p.module_description.font-sz-11
              = "To store: #{object.store.name} | Address: #{object.store.address} | Contact: #{object.store.contact_number}"
              -if _req_transfers.present?
                %span
                  Transfer ID:  
                  - _req_transfers.each do |rt|
                    = link_to "##{rt.id}", store_stock_transfer_path(@store,rt)
          %td= req_status_tag(object.status)
          %td.font-sz-12=object.created_at.strftime("%d %b %Y, %I:%M %p")
          %td.col-lg-2.col-xs-3.padding-top-20
            %a.m-btn.blue.view-recevd-req-details.right{"data-target" => "#showRequisitionModal", "data-toggle" => "modal", 'data-req-log-id'=> "#{object.id}", 'data-store-id'=>"#{@store.id}"} 
              %i.mdi-action-subject.left
              View
      
  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
- else
  .alert.alert-warning
    No requisitions has been sent from this store to another store yet.

app/views/stores/_store_racks_smartlist.html.haml
.main-section__content
  .example
    .example__content.p0
      .data-table-container{"aria-multiselectable" => "true", :role => "tablist"}
        %header.data-table-header
          .data-table-header__label.col-sm-2
            %span.fs-title Racks
          .data-table-header__actions.col-sm-10
            
            .form-group
              .right
                /= submit_tag "New Rack", name: nil, class: 'm-btn m-btn-teal'
                %a.m-btn.m-btn-teal{"data-target" =>"#showRakeOptionModal", "data-toggle" => "modal"}
                  %i.mdi-editor-format-list-numbered.left
                  New Racks 
              / .col-sm-5
              /   %a.m-btn.blue{"data-target" => "#resourceBulkUpload", "data-toggle" => "modal"} 
              /     %i.mdi-file-cloud-upload.left
              /     %span.hidden-sm.hidden-xs Upload Resource
              /     .clearfix    
                
        - unless smart_listing.empty?
          - smart_listing.collection.each do |object|
            .product-card.col-lg-3.col-xs-12.col-sm-12.padding-5
              .card.margin-t-b-0{:class=>"rack-card-#{object.id}"}
                .card-image
                  %a{:href => "#" }
                    = image_tag("/rack1.png", width: '200', :class => "img-thumbnail")
                .card-content.white-text
                  %p
                    = link_to "(##{object.id}-#{object.name})", :class => "white-text"
                .card-action
                  %span.float-l.badge.bincount 12
                  %a.addbin{"data-target"=>"#AddBinsModal", "data-toggle"=>"modal",:style=>"margin-left:5px;cursor:pointer;","title"=>"Add Bins","data-rack-id"=>"#{object.id}"}
                    .fa.fa-plus
                  %a{:href => "#{store_rack_bins_path(object.id)}" }
                    %i.mdi-content-send.smaller.float-r
          
          = smart_listing.paginate
          = smart_listing.pagination_per_page_links  
        - else
          .alert.alert-warning
            No rack found          
                

app/views/stores/edit.html.haml
.card
	%h3 Editing store

	= render 'form'

	= link_to 'Show', @store
	\|
	= link_to 'Back', stores_path

app/views/stores/return_store.html.haml
- links_arr = [{:title=>"All Stores",:url=>stores_path,:active_class=>""},{:title=>"Store: #{@store.name}",:url=>"#",:active_class=>"col-breadcrumb-selected"}]
- render_page_breadcrumbs(links_arr)  #ApplicationHelper
- @unit_currency = currency
.col-lg-3.col-sm-12.col-xs-12.col-xxs-12.padding-5
  .smallstat.box
    %i.fa.fa-money.orange
    %span.title.font-sz-12 Today's Return
    %span.value=number_to_currency(get_to_day_return_amount(@current_user.unit_id),unit: @unit_currency,format: "%u %n", precision: 2)
    .clearfix
.col-lg-3.col-sm-12.col-xs-12.col-xxs-12.padding-5
  .smallstat.box
    %i.fa.fa-check.green
    %span.title.font-sz-12 Today's Return Adjustment
    %span.value=number_to_currency(get_return_adjustment_amount(@current_user.unit_id),unit: @unit_currency,format: "%u %n", precision: 2)
    .clearfix
.col-lg-3.col-sm-12.col-xs-12.col-xxs-12.padding-5
  .smallstat.box
    %i.fa.fa-balance-scale.indigo
    %span.title.font-sz-12 Today's Remaning Balance
    %span.value=number_to_currency(get_to_day_return_amount(@current_user.unit_id) - get_return_adjustment_amount(@current_user.unit_id),unit: @unit_currency,format: "%u %n", precision: 2)
    .clearfix
.col-lg-3.col-sm-12.col-xs-12.col-xxs-12.padding-5
  .smallstat.box
    %i.fa.fa-cart-arrow-down.red
    %span.title.font-sz-12 Today's Item Count
    %span.value=get_to_day_distinct_product_count(@current_user.unit_id)
    .clearfix    
.clearfix  
.col-sm-3.padding-5
  .card
    .tabbable.tabs-left
      %ul.nav.nav-tabs.padding-none.width-100
        %li.active
          %a{"data-toggle" => "tab", :href => "#a"}
            %span.float-r.badge= @stocks.count
            Products and Stocks
        %li
          %a{"data-toggle" => "tab", :href => "#d"}
            %span.float-r.badge=@store.stock_credit_transfers.delivering.count + @store.stock_credit_transfers.return_delivering.count
            Manage Stock Transfers
        %li
          %a{"data-toggle" => "tab", :href => "#e"}
            %span.float-r.badge=@store.stock_audits.pending_audit.count
            Stock Audits
    .clearfix
    .filter-title.margin-t-b-0
      %i.mdi-action-open-in-new.left
      Quick Links
    .padding-5
      %a.m-btn.blue.width-100.margin-b-5.text-align-left.waves-effect.waves-light{"data-target" =>"#showTransferOptionModal", "data-toggle" => "modal"}
        %i.mdi-action-trending-neutral.left
        Transfer products
      %a.m-btn.blue.width-100.margin-b-5.text-align-left.waves-effect.waves-light{"data-target" =>"#showAuditOptionModal", "data-toggle" => "modal"}
        %i.mdi-av-shuffle.left
        New stock audit
      
.col-sm-9.padding-r-none                                       
  .tab-content
    #a.tab-pane.active
      .col-md-2.padding-l-r-none
        %h3.margin-t-none Products
      .col-md-10.padding-l-r-none
        = smart_listing_controls_for(:return_items, {class: "form-inline text-right"}) do
          .form-group.filter.input-append
            = select_tag :catrgory, options_from_collection_for_select(Category.all, "id", "name"), class: "search form-control", :prompt => "All categories"
          .form-group.filter.input-append
            = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off
          %button.btn.btn-primary.disabled{type: :submit}
            %span.glyphicon.glyphicon-search
      .col-md-12.padding-l-r-none
        = smart_listing_render :return_items

/ Transfer Option Modal
#showTransferOptionModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "showTransferOptionModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content.m-modal-content
      .modal-header.m-modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4#showTransferOptionModalLabel.modal-title Select transfer option
      .modal-body
        .col-md-12
          .col-md-3
            %h4 Option A
          .col-md-9
            .btn-group{:style=> "width:100%"}
              %a.btn.btn-default.dropdown-toggle.text-left.btn-social.btn-primary{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button",:style=> "width:100%"}
                %i.fa.fa-exchange
                Select business type
                %span.caret
              %ul.dropdown-menu.dropdown-menu-right{:role => "menu",:style=> "width:100%"}
                - @business_types.each do |business_type|
                  %li
                    %a{:href => "#{new_store_stock_transfer_path(@store)}?business_type=#{business_type}"}= business_type.humanize

        .clearfix
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

/ Audit Option Modal
#showAuditOptionModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "showAuditOptionModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content.m-modal-content
      .modal-header.m-modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4#showAuditOptionModalLabel.modal-title Select audit option
      .modal-body
        .col-md-12
          .col-md-3
            %h4 Option A
          .col-md-9
            .btn-group{:style=> "width:100%"}
              %a.btn.btn-default.dropdown-toggle.text-left.btn-social.btn-primary{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button",:style=> "width:100%"}
                %i.fa.fa-exchange
                Select business type
                %span.caret
              %ul.dropdown-menu.dropdown-menu-right{:role => "menu",:style=> "width:100%"}
                - @business_types.each do |business_type|
                  %li
                    %a{:href => "#{new_store_stock_audit_path(@store)}?business_type=#{business_type}"}= business_type.humanize
        .clearfix
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close