config/routes.rb
require 'sidekiq/web'

class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

Inventory::Application.routes.draw do

  resources :thirdparty_callbacks, only: [:index] do
    collection do
      
    end
  end

  resources :tag_groups
  resources :comprehensive_sale_reports, only: [:index] do
    collection do
      get 'bill_by_bill_report'
    end
  end

  resources :tag_groups

  resources :doc_types

  resources :check_informations

  resources :combo_items

  resources :addons_groups

  resources :proformas do
    collection do
      get 'fetch_orders'
    end
  end

  resources :financial_accounts do
    collection do
      get 'account_details'
    end
  end

  resources :incentive_rules
  resources :labels
  resources :areas do
    collection do
      get 'fetch_users'
    end
  end
  resources :zones do 
    collection do
      get 'fetch_users'
    end
  end
  resources :resource_order_history_details

  resources :resource_order_histories

  resources :user_targets

  resources :boxings

  resources :tags do
    collection do
      post "update_status"
    end
  end

  resources :packages do
    collection do
      get 'search_package_components'
    end
  end

  resources :model_actions

  resources :actions

  resources :reason_codes

  resources :master_models

  resources :cost_categories

  resources :money_refunds

  resources :return_policies do
    collection do
      post 'delete_return_cause'
    end
  end

  resources :cancelation_policies do
    collection do
      post 'delete_cancelation_cause'
    end
  end

  resources :vendor_product_prices do
    collection do
      post 'update_status'
    end
  end

  resources :delivery_charges

  resources :questions do 
    collection do
      post 'update_status'
    end
  end

  resources :customer_states do 
    collection do 
      post "update_status"
    end
  end
  resources :inventory_dashboards, only: [:index]
  resources :customer_statuses
  resources :user_work_statuses
  resources :visiting_histories
  resources :upi_merchants
  resources :resource_product_stocks
  resources :payment_wallets
  resources :inspections
  resources :bill_destinations
  resources :item_preferences
  resources :menu_mappings
  post "/menu_mappings/:id/update_status", to: 'menu_mappings#update_status', as: 'menu_mapping_update_status'
  resources :days
  resources :sizes
  resources :colors
  resources :sale_rules do
    collection do
      get 'all_sale_rules'
    end
  end
  resources :sales_persons do
    collection do
      post 'allot_resource'
      post 'allot_resource_map'
      post "delete_user_resource"
      post "import"
      get "get_allocations"
      post "create_allocation"
      post "remove_allocation"
      post "update_allocation"
      post "create_recursive_allocation"
      get "sample_csv"
      post "remove_all_by_date"
    end  
  end  
  match '/paytm_payment' => 'paytm#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'paytm#verify_payment', via: [:post]

  resources :product_religions
  resources :allergies
  resources :parties
  resources :customer_queue_states
  get "outlet_types/save"
  resources :outlet_types
  get "more_infos/save"
  resources :more_infos
  resources :unit_images
  resources :quotations
  resources :customers do
    collection do
      post '/import',to: "customers#import", as: "import"
      get 'find'
      get 'find_by_login'
    end
    resources :addresses
    resources :customer_profiles
    resources :addresses
  end
  resources :otps
  resources :own_customers do
    resources :own_customer_addresses
  end
  resources :process_compositions
  resources :production_processes do
    member do
      put '/toggle_trash', to: "production_processes#toggle_trash", as: "toggle_trash"
    end
  end
  resources :own_customers do
    resources :own_customer_addresses
  end
  resources :denominations
  resources :countries
  resources :cash_outs
  resources :cash_ins
  resources :cash_handlings
  resources :percentages
  resources :conjugated_units
  resources :stock_purchase_payments, only: [:create]
  resources :news_event_galleries
  resources :feedback_options
  resources :feedbacks
  resources :news_events
  resources :resource_states
  resources :onboarding do
    collection do
      post  '/import',   to: "onboarding#import", as: "import"
    end
  end
  resources :onboarding, only: [:show]
  resources :media
  resources :developer_apps
  resources :buffet_rules, except: [:destroy, :edit, :update]
  resources :buffet_groups, except: [:destroy]
  resources :product_attribute_groups
  resources :product_attribute_sets do
    collection do
      get 'seed'
    end
  end
  resources :product_attribute_keys
  resources :product_attribute_options
  resources :reservations do
    collection do
      get :reservations_list
    end  
  end  
  resources :availabilities
  resources :slots
  resources :resources do
    collection do
      get 'fetch_active_menu_cards'
      get 'get_resources'
      post 'change_resource_state'
      post 'swap_resource'
      get 'retail_shops_list'
      get 'export_resource'
      post '/import',   to: "resources#import", as: "import"
      post '/import_commission', to: "resources#import_commission", as:"import_commission"
      post '/import_beneficiary', to: "resources#import_beneficiary", as:"import_beneficiary"
      get 'sample_commission_csv'
      get 'find'
      get 'fetch_section_resources'
      get 'fetch_active_menu_products'
    end
    resources :commission_rules
    resources :beneficiaries
  end
  resources :commission_rules do
    collection do
      post "quick_update"
    end
  end
  resources :resource_types
  resources :beneficiaries

  resources :customer_queues

  resources :lots, only: [:show] do
    collection do
      put "delete_lot_sale_rule"
      put "lot_quick_update"
    end
  end
  resources :delivery_reports, only: [:index] do 
    collection do 
      get "slot_specific_delivery_reports"
      get "delivery_boys_report"
    end
  end
  mount Rscratch::Engine => '/rscratch'
  resources :reprint_details,only: [:index]

  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do
      resources :doc_types
      resources :check_informations, only: [:index, :update, :show] do
        collection do 
        end  
      end 
      resources :financial_accounts
      resources :customer_product_wishlists do
        collection do
          post 'remove_product'
        end  
      end  
      resources :financial_accounts_transactions do
        collection do 
          post 'debit'
        end  
      end  
      resources :proformas
      resources :boxings, only: [:create, :update, :show] do
        collection do
          post 'search_by_barcode'
          post 'create_box'
          post 'create_box_item'
          post 'remove_box_item'
        end
      end
      resources :reason_codes, only: [:index] do
        collection do
          get 'master_models'
          get 'model_actions'
        end
      end
      resources :warehouses do 
        collection do 
          post 'put_product'
          post 'pick_product'
          get 'product_bins'
          get 'bin_product_quantity'
        end
      end
      resources :packages do 
        collection do 
          get 'required_product_fields'
          post 'add_product'
          post 'package_creation'
          post 'edit_package_name'
          post 'create_package_unit'
          post 'edit_package_unit'
          post 'add_package_unit_product'
          post 'add_product_composition'
          get 'package_details'
          post 'add_package_component'
          get 'package_component_details'
          post 'remove_package_unit'
          post 'remove_package_unit_product'
        end
      end
      resources :cost_categories
      resources :beneficiaries, only: [:index]
      resources :labels, only: [:index]
      resources :return_items, only: [:index, :update]
      resources :questions, only: [:index, :show]
      resources :return_item_reports
      resources :user_login_logouts
      resources :delivery_addresses
      resources :bill_reprints, only: [:index, :create, :show]
      resources :user_work_statuses, only: [:create] do
        collection do
          get "work_statuses"
        end  
      end  
      resources :customer_communications, only: [:create] do
        collection do
          get "communications"
        end
      end
      resources :customer_tags, only: [:index,:create]
      resources :customer_notes, only: [:index,:create] do 
        collection do 
          get "notes"
        end
      end
      resources :resource_product_stocks, only: [:create]
      resources :visiting_histories, only: [:create, :index, :show]
      resources :item_preferences, only: [:index]
      resources :bill_destinations, only: [:index]
      resources :upi_merchants, only: [:index]
      resources :delivery_boys do
        collection do
          post "sign_in"
        end
      end
      resources :quotations
      resources :configurations, only: [:index]
      resources :days, only: [:index] do
        collection do
          get "menu_mapping"
        end  
      end
      resources :offers , only: [:index] do
        collection do
          post 'get_offers'
        end
      end 
      resources :units, only: [:index, :show] do
        collection do
          get "get_units"
          get "units_sales_persons"
        end  
      end  
      resources :sections, only: [:show] do
        collection do
          get 'section_tax_groups'
        end
      end
      resources :menu_cards, only: [:index, :show] do
        collection do
          get 'mp_sale_rules'
          get 'download_menu_cards'
        end
        member do
          get "product/:product_id", to: "menu_cards#product"
        end
      end
      resources :boutique_capillaries do
        collection do

app/models/app_configuration.rb
class AppConfiguration < ActiveRecord::Base
  attr_accessible :config_key, :config_value

  # => Model validations
  validates :config_key,         :presence => true
  validates :config_value,       :presence => true

  after_create :setup_organization_structure, if: :is_business_type_config?

  # => Model Scopes
  scope :set_key,   lambda {|key|where(["config_key=?", key])}
  scope :set_keys,   lambda {|keys|where(["config_key IN(?)", keys])}
  scope :tsp_configuration,  lambda { where("config_key IN ('tsp_module','tsp_get_resource_stock','accept_new_order','future_order','item_remarks','pedler_work_on_offline','live_tracking_and_timeline','resource_order_history','distribution_config','b2b_billing')")}

  def self.get_config_value(config_key)
    # conf = AppConfiguration.find(:first, :conditions => ['config_key =?', config_key]) #commented due to rails4 migration
    conf = AppConfiguration.where("config_key =?", config_key).first
    config_value = conf.present? ? conf.config_value : 'disabled'
  end

  def self.get_config_value_of_report(config_key)
    conf = AppConfiguration.find_by(config_key: config_key)
    config_value = conf.present? ? conf.config_value : 2
  end

  def self.get_config(config_key)
    conf = AppConfiguration.find_by(config_key: config_key)
    config_value = conf.present? ? conf.config_value : ''
  end

  def self.load_basic_configurations()
  	AppConfigurationManagement.load_basic_configurations("req_auto_adjust", 1)
  	AppConfigurationManagement.load_basic_configurations("purchase_order_auto_adjust", 1)
    AppConfigurationManagement.load_basic_configurations("owner_will_crud_menu", 1)
    AppConfigurationManagement.load_basic_configurations("low_over_stock_alert", 0)
  end

  def self.create_for key, value
    config = AppConfiguration.create(:config_key => key, :config_value => value)
  end

  def self.register_subdomain_with_modules subdomain
    AppConfiguration.create_for "site_id", subdomain.id
    AppConfiguration.create_for "site_url", subdomain.url
    AppConfiguration.create_for "site_title", subdomain.name
    # Load subdomain modules
    subdomain.properties.each do |key, value|
      AppConfiguration.create_for key, value
    end
  end

  def is_business_type_config?
    key = (self.config_key == "business_type") ? true : false
  end

  def setup_organization_structure
    # Add unittypes
    if self.config_value == "fnb" or self.config_value == "fnb_fd" or self.config_value == "fnb_qsr"
      Unittype.create([{:unit_type_name => "Distribution Center"}, {:unit_type_name => "Outlet"}])
    elsif self.config_value == "retail"
      Unittype.create([{:unit_type_name => "Distribution Center"}, {:unit_type_name => "Outlet"}])
    end
    # Add user roles
    if self.config_value == "fnb" or self.config_value == "fnb_qsr"
      Role.create([{:name => "dc_manager"}, {:name => "outlet_manager"}, {:name => "cashier"}])
    elsif self.config_value == "fnb_fd"
      Role.create([{:name => "dc_manager"}, {:name => "outlet_manager"}, {:name => "cashier"}, {:name => "waiter"}, {:name => "bartender"}])
    elsif self.config_value == "retail"
      Role.create([{:name => "dc_manager"}, {:name => "outlet_manager"}, {:name => "cashier"}])
    end
  end
end

app/controllers/app_configurations_controller.rb
class AppConfigurationsController < ApplicationController
  load_and_authorize_resource :except => [:save_config] #CanCan Authentication
  layout "material"

  before_filter :set_module_details

  # GET /app_configurations
  # GET /app_configurations.json
  def index
    @app_configurations = AppConfiguration.all
    # url = "http://services.groupkt.com/state/search/IND?text="
    # states_json = RestClient::Request.execute(method: :get, url: url)
    # @states = JSON.parse (states_json)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @app_configurations }
    end
  end

  # GET /app_configurations/1
  # GET /app_configurations/1.json
  def show
    @app_configuration = AppConfiguration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_configuration }
    end
  end

  # GET /app_configurations/new
  # GET /app_configurations/new.json
  def new
    @app_configuration = AppConfiguration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app_configuration }
    end
  end

  # GET /app_configurations/1/edit
  def edit
    @app_configuration = AppConfiguration.find(params[:id])
  end

  # POST /app_configurations
  # POST /app_configurations.json
  def create
    @app_configuration = AppConfiguration.new(params[:app_configuration])
    respond_to do |format|
      if @app_configuration.save
        format.html { redirect_to @app_configuration, notice: 'App configuration was successfully added.' }
        format.js { render nothing: true }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js { render nothing: true }
        format.json { render json: @app_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /app_configurations/1
  # PUT /app_configurations/1.json
  def update
    @app_configuration = AppConfiguration.find(params[:id])

    respond_to do |format|
      if @app_configuration.update_attributes(params[:app_configuration])
        format.html { redirect_to @app_configuration, notice: 'App configuration was successfully updated.' }
        format.js { render nothing: true }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js { render nothing: true }
        format.json { render json: @app_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_configurations/1
  # DELETE /app_configurations/1.json
  def destroy
    @app_configuration = AppConfiguration.find(params[:id])
    @app_configuration.destroy

    respond_to do |format|
      format.html { redirect_to app_configurations_url }
      format.json { head :no_content }
    end
  end

  def basic_configurations
    AppConfiguration.load_basic_configurations()

    respond_to do |format|
      format.html { redirect_to app_configurations_path, notice: 'Basic app configuration was successfully loaded.' }
      format.json { head :no_content }
    end
  end

  def printers
    @printers = Printer.all
    @printer = Printer.new
  end

  def save_config
    @app_config = AppConfiguration.set_key(params[:config_key])
    if @app_config.present?
      @app_config.first.update_attribute(:config_value,params[:config_value])
    else
      @app_config = AppConfiguration.create(:config_key=> params[:config_key],:config_value=> params[:config_value])
    end
    respond_to do |format|
      format.json { render json: @app_config }
    end
  end

  def update_account
    begin
      @account = Account.find_by_subdomain(request.subdomain)
      @account.update_attribute(params[:column_name], params[:column_value])
      respond_to do |format|
        format.json { render json: @account.reload }
      end
    rescue Exception => e
      Rscratch::Exception.log e,request
      respond_to do |format|
        format.json { render json: {:error=> e.message.to_s}, status: :unprocessable_entity }
      end
    end
  end
  def check_app_config
    config_status = AppConfiguration.get_config(params[:config_key])
    respond_to do |format|
      format.json { render json: {status:config_status} }
    end
  end
  private

  def set_module_details
    @module_id = "app_config"
    @module_title = "Application Configurations"
  end
end

app/helpers/app_configurations_helper.rb
module AppConfigurationsHelper
end

app/views/app_configurations/_form.html.haml
.panel.panel-default
  .panel-heading Default Settings
  .panel-body
    = form_for @app_configuration do |f|
      - if @app_configuration.errors.any?
        #error_explanation
          %h2= "#{pluralize(@app_configuration.errors.count, "error")} prohibited this app_configuration from being saved:"
          %ul
            - @app_configuration.errors.full_messages.each do |msg|
              %li= msg
      - if @app_configurations.present?
        #callout-stacked-modals.bs-callout.bs-callout-success
          %h4 Requisition Module
          - if @req_auto_adjust.present? 
            Auto adjust store requisition :
            %label
              %input#optionsRadios1{ :checked => ( @req_auto_adjust == "1" ? true : false ), :name => "req_auto_adjust", :type => "radio", :value => "1"}
                Yes
            %label
              %input#optionsRadios2{:checked => ( @req_auto_adjust == "0" ? true : false ), :name => "req_auto_adjust", :type => "radio", :value => "0"}
                No
          - else
            %a.btn.btn-primary{:href => basic_configurations_app_configurations_path, :role => "button"} Load
            
        #callout-stacked-modals.bs-callout.bs-callout-warning
          %h4 Purchase Order Module
          - if @purchase_order_auto_adjust.present? 
            Auto adjust purchase order : 
            %label
              %input#optionsRadios1{ :checked => ( @purchase_order_auto_adjust == "1" ? true : false ), :name => "purchase_order_auto_adjust", :type => "radio", :value => "1"}
                Yes
            %label
              %input#optionsRadios2{:checked => ( @purchase_order_auto_adjust == "0" ? true : false ), :name => "purchase_order_auto_adjust", :type => "radio", :value => "0"}
                No
          - else
            %a.btn.btn-primary{:href => basic_configurations_app_configurations_path, :role => "button"} Load

        #callout-stacked-modals.bs-callout.bs-callout-danger
          %h4 Menu Module
          - if @owner_will_crud_menu.present? 
            Owner will create edit delete menu : 
            %label
              %input#optionsRadios1{ :checked => ( @owner_will_crud_menu == "1" ? true : false ), :name => "owner_will_crud_menu", :type => "radio", :value => "1"}
                Yes
            %label
              %input#optionsRadios2{:checked => ( @owner_will_crud_menu == "0" ? true : false ), :name => "owner_will_crud_menu", :type => "radio", :value => "0"}
                No
          - else
            %a.btn.btn-primary{:href => basic_configurations_app_configurations_path, :role => "button"} Load

        #callout-stacked-modals.bs-callout.bs-callout-success
          %h4 Stock Management Module
          - if @low_over_stock_alert.present? 
            Enable low/ over stock alert : 
            %label
              %input#optionsRadios1{ :checked => ( @low_over_stock_alert == "1" ? true : false ), :name => "low_over_stock_alert", :type => "radio", :value => "1"}
                Yes
            %label
              %input#optionsRadios2{:checked => ( @low_over_stock_alert == "0" ? true : false ), :name => "low_over_stock_alert", :type => "radio", :value => "0"}
                No
          - else
            %a.btn.btn-primary{:href => basic_configurations_app_configurations_path, :role => "button"} Load

        .actions
          = f.submit 'Save', :class => 'btn btn-success btn-lg'
      - else
        =# AppConfiguration.load_basic_configurations()
        .jumbotron
          %h1 Hello, user!
          %p It seems like you did not load your basic configurations.
          %p
            %a.btn.btn-primary.btn-lg{:href => basic_configurations_app_configurations_path, :role => "button"} Load basic configurations

app/views/app_configurations/_printer_listing.html.haml
%h1 Listing printers

%table.table.table-bordered
  %tr
    %th Name
    %th Ip
    %th Assignable
    %th Actions

  - current_user.unit.printers.each do |printer|
    %tr
      %td= printer.name
      %td= printer.ip
      %td= printer.assignable.name
      %td
        = link_to 'Edit', edit_printer_path(printer)
        = link_to 'Destroy', printer, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/app_configurations/_sidebar.html.haml
/ %ul.nav.nav-pills.nav-stacked
/   %li.active{:role => "presentation"}
/     %a{:href => app_configurations_path} Home
/   %li{:role => "presentation"}
/     %a{:href => printers_app_configurations_path} Printers
.card
  .clearfix
  .filter-title.margin-t-b-0 
    %i.mdi-av-games.left
    Modules
  .tabbable.tabs-left
    %ul.nav.nav-tabs.padding-none
      %li
        %a{"data-toggle" => "", :href => app_configurations_path} 
          General
      %li
        %a{"data-toggle" => "", :href => app_configurations_path} 
          Orders
      %li
        %a{"data-toggle" => "", :href => app_configurations_path} 
          Inventory            
      %li.active
        %a{"data-toggle" => "", :href => printers_app_configurations_path}
          Printers   
      %li
        %a{"data-toggle" => "", :href => app_configurations_path}
          Advanced             
      %li
        %a{"data-toggle" => "", :href => app_configurations_path}
          Clear Data 

app/views/app_configurations/edit.html.haml
%h1 Editing app_configuration

= render 'form'

= link_to 'Show', @app_configuration
\|
= link_to 'Back', app_configurations_path

app/views/app_configurations/new.html.haml
%h1 New app_configuration

= render 'form'

= link_to 'Back', app_configurations_path

app/views/app_configurations/printers.html.haml
= render "layouts/flash" 

.col-md-12
  .panel.panel-default
    .panel-heading Printer Settings
    .panel-body

      .col-md-9
        = render "printer_listing"
      .col-md-3.well
        = render partial:"/printers/form"

app/views/app_configurations/show.html.haml
%p#notice= notice

%p
  %b Config key:
  = @app_configuration.config_key
%p
  %b Config value:
  = @app_configuration.config_value

= link_to 'Edit', edit_app_configuration_path(@app_configuration)
\|
= link_to 'Back', app_configurations_path