config/routes.rb
require 'sidekiq/web'

class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

Inventory::Application.routes.draw do

  resources :thirdparty_callbacks, only: [:index] do
    collection do
      
    end
  end

  resources :tag_groups
  resources :comprehensive_sale_reports, only: [:index] do
    collection do
      get 'bill_by_bill_report'
    end
  end

  resources :tag_groups

  resources :doc_types

  resources :check_informations

  resources :combo_items

  resources :addons_groups

  resources :proformas do
    collection do
      get 'fetch_orders'
    end
  end

  resources :financial_accounts do
    collection do
      get 'account_details'
    end
  end

  resources :incentive_rules
  resources :labels
  resources :areas do
    collection do
      get 'fetch_users'
    end
  end
  resources :zones do 
    collection do
      get 'fetch_users'
    end
  end
  resources :resource_order_history_details

  resources :resource_order_histories

  resources :user_targets

  resources :boxings

  resources :tags do
    collection do
      post "update_status"
    end
  end

  resources :packages do
    collection do
      get 'search_package_components'
    end
  end

  resources :model_actions

  resources :actions

  resources :reason_codes

  resources :master_models

  resources :cost_categories

  resources :money_refunds

  resources :return_policies do
    collection do
      post 'delete_return_cause'
    end
  end

  resources :cancelation_policies do
    collection do
      post 'delete_cancelation_cause'
    end
  end

  resources :vendor_product_prices do
    collection do
      post 'update_status'
    end
  end

  resources :delivery_charges

  resources :questions do 
    collection do
      post 'update_status'
    end
  end

  resources :customer_states do 
    collection do 
      post "update_status"
    end
  end
  resources :inventory_dashboards, only: [:index]
  resources :customer_statuses
  resources :user_work_statuses
  resources :visiting_histories
  resources :upi_merchants
  resources :resource_product_stocks
  resources :payment_wallets
  resources :inspections
  resources :bill_destinations
  resources :item_preferences
  resources :menu_mappings
  post "/menu_mappings/:id/update_status", to: 'menu_mappings#update_status', as: 'menu_mapping_update_status'
  resources :days
  resources :sizes
  resources :colors
  resources :sale_rules do
    collection do
      get 'all_sale_rules'
    end
  end
  resources :sales_persons do
    collection do
      post 'allot_resource'
      post 'allot_resource_map'
      post "delete_user_resource"
      post "import"
      get "get_allocations"
      post "create_allocation"
      post "remove_allocation"
      post "update_allocation"
      post "create_recursive_allocation"
      get "sample_csv"
      post "remove_all_by_date"
    end  
  end  
  match '/paytm_payment' => 'paytm#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'paytm#verify_payment', via: [:post]

  resources :product_religions
  resources :allergies
  resources :parties
  resources :customer_queue_states
  get "outlet_types/save"
  resources :outlet_types
  get "more_infos/save"
  resources :more_infos
  resources :unit_images
  resources :quotations
  resources :customers do
    collection do
      post '/import',to: "customers#import", as: "import"
      get 'find'
      get 'find_by_login'
    end
    resources :addresses
    resources :customer_profiles
    resources :addresses
  end
  resources :otps
  resources :own_customers do
    resources :own_customer_addresses
  end
  resources :process_compositions
  resources :production_processes do
    member do
      put '/toggle_trash', to: "production_processes#toggle_trash", as: "toggle_trash"
    end
  end
  resources :own_customers do
    resources :own_customer_addresses
  end
  resources :denominations
  resources :countries
  resources :cash_outs
  resources :cash_ins
  resources :cash_handlings
  resources :percentages
  resources :conjugated_units
  resources :stock_purchase_payments, only: [:create]
  resources :news_event_galleries
  resources :feedback_options
  resources :feedbacks
  resources :news_events
  resources :resource_states
  resources :onboarding do
    collection do
      post  '/import',   to: "onboarding#import", as: "import"
    end
  end
  resources :onboarding, only: [:show]
  resources :media
  resources :developer_apps
  resources :buffet_rules, except: [:destroy, :edit, :update]
  resources :buffet_groups, except: [:destroy]
  resources :product_attribute_groups
  resources :product_attribute_sets do
    collection do
      get 'seed'
    end
  end
  resources :product_attribute_keys
  resources :product_attribute_options
  resources :reservations do
    collection do
      get :reservations_list
    end  
  end  
  resources :availabilities
  resources :slots
  resources :resources do
    collection do
      get 'fetch_active_menu_cards'
      get 'get_resources'
      post 'change_resource_state'
      post 'swap_resource'
      get 'retail_shops_list'
      get 'export_resource'
      post '/import',   to: "resources#import", as: "import"
      post '/import_commission', to: "resources#import_commission", as:"import_commission"
      post '/import_beneficiary', to: "resources#import_beneficiary", as:"import_beneficiary"
      get 'sample_commission_csv'
      get 'find'
      get 'fetch_section_resources'
      get 'fetch_active_menu_products'
    end
    resources :commission_rules
    resources :beneficiaries
  end
  resources :commission_rules do
    collection do
      post "quick_update"
    end
  end
  resources :resource_types
  resources :beneficiaries

  resources :customer_queues

  resources :lots, only: [:show] do
    collection do
      put "delete_lot_sale_rule"
      put "lot_quick_update"
    end
  end
  resources :delivery_reports, only: [:index] do 
    collection do 
      get "slot_specific_delivery_reports"
      get "delivery_boys_report"
    end
  end
  mount Rscratch::Engine => '/rscratch'
  resources :reprint_details,only: [:index]

  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do
      resources :doc_types
      resources :check_informations, only: [:index, :update, :show] do
        collection do 
        end  
      end 
      resources :financial_accounts
      resources :customer_product_wishlists do
        collection do
          post 'remove_product'
        end  
      end  
      resources :financial_accounts_transactions do
        collection do 
          post 'debit'
        end  
      end  
      resources :proformas
      resources :boxings, only: [:create, :update, :show] do
        collection do
          post 'search_by_barcode'
          post 'create_box'
          post 'create_box_item'
          post 'remove_box_item'
        end
      end
      resources :reason_codes, only: [:index] do
        collection do
          get 'master_models'
          get 'model_actions'
        end
      end
      resources :warehouses do 
        collection do 
          post 'put_product'
          post 'pick_product'
          get 'product_bins'
          get 'bin_product_quantity'
        end
      end
      resources :packages do 
        collection do 
          get 'required_product_fields'
          post 'add_product'
          post 'package_creation'
          post 'edit_package_name'
          post 'create_package_unit'
          post 'edit_package_unit'
          post 'add_package_unit_product'
          post 'add_product_composition'
          get 'package_details'
          post 'add_package_component'
          get 'package_component_details'
          post 'remove_package_unit'
          post 'remove_package_unit_product'
        end
      end
      resources :cost_categories
      resources :beneficiaries, only: [:index]
      resources :labels, only: [:index]
      resources :return_items, only: [:index, :update]
      resources :questions, only: [:index, :show]
      resources :return_item_reports
      resources :user_login_logouts
      resources :delivery_addresses
      resources :bill_reprints, only: [:index, :create, :show]
      resources :user_work_statuses, only: [:create] do
        collection do
          get "work_statuses"
        end  
      end  
      resources :customer_communications, only: [:create] do
        collection do
          get "communications"
        end
      end
      resources :customer_tags, only: [:index,:create]
      resources :customer_notes, only: [:index,:create] do 
        collection do 
          get "notes"
        end
      end
      resources :resource_product_stocks, only: [:create]
      resources :visiting_histories, only: [:create, :index, :show]
      resources :item_preferences, only: [:index]
      resources :bill_destinations, only: [:index]
      resources :upi_merchants, only: [:index]
      resources :delivery_boys do
        collection do
          post "sign_in"
        end
      end
      resources :quotations
      resources :configurations, only: [:index]
      resources :days, only: [:index] do
        collection do
          get "menu_mapping"
        end  
      end
      resources :offers , only: [:index] do
        collection do
          post 'get_offers'
        end
      end 
      resources :units, only: [:index, :show] do
        collection do
          get "get_units"
          get "units_sales_persons"
        end  
      end  
      resources :sections, only: [:show] do
        collection do
          get 'section_tax_groups'
        end
      end
      resources :menu_cards, only: [:index, :show] do
        collection do
          get 'mp_sale_rules'
          get 'download_menu_cards'
        end
        member do
          get "product/:product_id", to: "menu_cards#product"
        end
      end
      resources :boutique_capillaries do
        collection do

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :color, :icon, :name, :status, :tag_type, :tag_group_id
  has_attached_file :icon, :styles => { :medium => "250x250>", :thumb => "60x60>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
  has_many :customers,through: :customer_tag 
  has_and_belongs_to_many :menu_products
  belongs_to :tag_group
  #Model scope 
  scope :active, lambda { where(["status = ?",'active']) }
end

app/controllers/api/v2/tags_controller.rb
module Api
	module V2
		class TagsController < ApplicationController
			api :GET, '/api/v2/tags', "List of all tags. (Authorization header required for authentication)"
      param :email, String, :required => true, :desc => "Email ID of user, who is sending the request."
      param :device_id, String, :required => true, :desc => "ID of registered device (If its a request from portal send YOTTO05 instead)."
			def index
				@tags = Tag.where("status=?","active")
			end 
		end
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new
    @tag_groups = TagGroup.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
    @tag_groups = TagGroup.all
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
        format.json { render json: tags_path, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
  def update_status
    tag = Tag.find(params[:id])
    tag.update_attribute(:status,params[:status])
    respond_to do |format|
      format.json { render json: tag }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def tag_params
      params.require(:tag).permit(:color, :icon, :name, :status, :tag_type, :tag_group_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg
  .col-sm-4
    .form-group
      .col-sm-4
        = f.label :name
      .col-sm-4
        = f.text_field :name
    %br
    .form-group  
      .col-sm-4
        = f.label :icon
      .col-sm-4  
        = f.file_field :icon
    %br 
    .form-group
      .col-sm-4
        = f.label :color
      .col-sm-4
        = f.text_field :color, :type=>"color"
    %br
    .form-group
      .col-sm-4
        = f.label :tag_group_id
      .col-sm-4 
        = f.select :tag_group_id, options_for_select(@tag_groups.present? ? @tag_groups.map{ |tg| [tg.name, tg.id] } : "",@tag.tag_group_id), { include_blank: "Select Tag Group"}, {:class => "form-control", :required=> false,:style=>"width:150px;"} 
    %br
    .form-group
      .col-sm-4
        = f.label :status
      .col-sm-4 
        = f.select :status, options_for_select({"Active" => "active","Inactive" => "inactive"},@tag.status), { include_blank: "Select Status"}, {:class => "form-control", :required=> true,:style=>"width:150px;"} 
    %br
    .form-froup
      .col-sm-4
        = f.label :tag_type
      .col-sm-4  
        = f.select :tag_type, options_for_select({"Product" => "Product","Customer" => "customer"},@tag.tag_type), { include_blank: "Select Tag type"}, {:class => "form-control", :required=> true,:style=>"width:150px;"} 
    %br
    %br
    .actions
      = f.submit 'Save' ,:class=>"btn btn-success"

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
:css
  .circle {
    height: 50px;
    width: 50px;
    border-radius: 100%;
  }

.main-section__content
  .example
    .example__content.p0
      .data-table-container
        %header.data-table-header
          .data-table-header__label
            %span.fs-title Listing Tags
          .data-table-header__actions
            %a.m-btn.m-btn-teal{:href => "#{new_tag_path}"}
              %i.mdi-content-add.left
              New Tag
        %table.data-table    
          %tr
            %th.col-lg-4 
              %strong Tag Name
            %th.col-lg-2 
              %strong Color
            %th.col-lg-1 
              %strong Icon
            %th.col-lg-1 
              %strong Type
            %th.col-lg-1 
              %strong Status
            %th.col-lg-2 
              %strong Action
          - @tags.each do |object|
            %tr
              %td.col-lg-2= object.name
              %td.col-lg-2
                .circle{:style=>"background-color:#{object.color}"}
              %td.col-lg-2= object.icon.present? ? image_tag("#{object.icon}", width: '50', :class => "img-thumbnail") : image_tag("icons/product-box-128.png", width: '50', :class => "img-thumbnail")
              %td.col-lg-1
                = object.tag_type
              %td.col-lg-1
                - tag_status = object.status == 'active' ? true : false
                .switch.padding-5
                  %label
                    = check_box_tag :status, 'enable', tag_status, {"data-value-active"=>"active","data-value-inactive"=>"inactive", "class"=>"update_tag_status", "data-tag-id"=>object.id }
                    %span.lever.margin-l-none
              %td.col-lg-4
                %a.m-btn.green.m-btn-low-padding{:href => "#{tag_path(object)}", :title => "View Tag"}
                  %i.mdi-action-visibility
                %a.m-btn.orange.m-btn-low-padding{:href => "#{edit_tag_path(object)}", :title => "Edit Tag"} 
                  %i.mdi-editor-border-color
                %a.m-btn.red.m-btn-low-padding{:title => "Remove Tag",:href => "#{tag_path(object)}",:method => :delete,:method => :delete, :data => { :confirm => 'Are you sure?' } }
                  %i.mdi-action-delete

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

app/views/tags/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @tag.name
%p
  %b Icon:
  = @tag.icon
%p
  %b Color:
  = @tag.color
%p
  %b Tag type:
  = @tag.tag_type
%p
  %b Status:
  = @tag.status

= link_to 'Edit', edit_tag_path(@tag)
\|
= link_to 'Back', tags_path