config/routes.rb
require 'sidekiq/web'

class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

Inventory::Application.routes.draw do

  resources :thirdparty_callbacks, only: [:index] do
    collection do
      
    end
  end

  resources :tag_groups
  resources :comprehensive_sale_reports, only: [:index] do
    collection do
      get 'bill_by_bill_report'
    end
  end

  resources :tag_groups

  resources :doc_types

  resources :check_informations

  resources :combo_items

  resources :addons_groups

  resources :proformas do
    collection do
      get 'fetch_orders'
    end
  end

  resources :financial_accounts do
    collection do
      get 'account_details'
    end
  end

  resources :incentive_rules
  resources :labels
  resources :areas do
    collection do
      get 'fetch_users'
    end
  end
  resources :zones do 
    collection do
      get 'fetch_users'
    end
  end
  resources :resource_order_history_details

  resources :resource_order_histories

  resources :user_targets

  resources :boxings

  resources :tags do
    collection do
      post "update_status"
    end
  end

  resources :packages do
    collection do
      get 'search_package_components'
    end
  end

  resources :model_actions

  resources :actions

  resources :reason_codes

  resources :master_models

  resources :cost_categories

  resources :money_refunds

  resources :return_policies do
    collection do
      post 'delete_return_cause'
    end
  end

  resources :cancelation_policies do
    collection do
      post 'delete_cancelation_cause'
    end
  end

  resources :vendor_product_prices do
    collection do
      post 'update_status'
    end
  end

  resources :delivery_charges

  resources :questions do 
    collection do
      post 'update_status'
    end
  end

  resources :customer_states do 
    collection do 
      post "update_status"
    end
  end
  resources :inventory_dashboards, only: [:index]
  resources :customer_statuses
  resources :user_work_statuses
  resources :visiting_histories
  resources :upi_merchants
  resources :resource_product_stocks
  resources :payment_wallets
  resources :inspections
  resources :bill_destinations
  resources :item_preferences
  resources :menu_mappings
  post "/menu_mappings/:id/update_status", to: 'menu_mappings#update_status', as: 'menu_mapping_update_status'
  resources :days
  resources :sizes
  resources :colors
  resources :sale_rules do
    collection do
      get 'all_sale_rules'
    end
  end
  resources :sales_persons do
    collection do
      post 'allot_resource'
      post 'allot_resource_map'
      post "delete_user_resource"
      post "import"
      get "get_allocations"
      post "create_allocation"
      post "remove_allocation"
      post "update_allocation"
      post "create_recursive_allocation"
      get "sample_csv"
      post "remove_all_by_date"
    end  
  end  
  match '/paytm_payment' => 'paytm#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'paytm#verify_payment', via: [:post]

  resources :product_religions
  resources :allergies
  resources :parties
  resources :customer_queue_states
  get "outlet_types/save"
  resources :outlet_types
  get "more_infos/save"
  resources :more_infos
  resources :unit_images
  resources :quotations
  resources :customers do
    collection do
      post '/import',to: "customers#import", as: "import"
      get 'find'
      get 'find_by_login'
    end
    resources :addresses
    resources :customer_profiles
    resources :addresses
  end
  resources :otps
  resources :own_customers do
    resources :own_customer_addresses
  end
  resources :process_compositions
  resources :production_processes do
    member do
      put '/toggle_trash', to: "production_processes#toggle_trash", as: "toggle_trash"
    end
  end
  resources :own_customers do
    resources :own_customer_addresses
  end
  resources :denominations
  resources :countries
  resources :cash_outs
  resources :cash_ins
  resources :cash_handlings
  resources :percentages
  resources :conjugated_units
  resources :stock_purchase_payments, only: [:create]
  resources :news_event_galleries
  resources :feedback_options
  resources :feedbacks
  resources :news_events
  resources :resource_states
  resources :onboarding do
    collection do
      post  '/import',   to: "onboarding#import", as: "import"
    end
  end
  resources :onboarding, only: [:show]
  resources :media
  resources :developer_apps
  resources :buffet_rules, except: [:destroy, :edit, :update]
  resources :buffet_groups, except: [:destroy]
  resources :product_attribute_groups
  resources :product_attribute_sets do
    collection do
      get 'seed'
    end
  end
  resources :product_attribute_keys
  resources :product_attribute_options
  resources :reservations do
    collection do
      get :reservations_list
    end  
  end  
  resources :availabilities
  resources :slots
  resources :resources do
    collection do
      get 'fetch_active_menu_cards'
      get 'get_resources'
      post 'change_resource_state'
      post 'swap_resource'
      get 'retail_shops_list'
      get 'export_resource'
      post '/import',   to: "resources#import", as: "import"
      post '/import_commission', to: "resources#import_commission", as:"import_commission"
      post '/import_beneficiary', to: "resources#import_beneficiary", as:"import_beneficiary"
      get 'sample_commission_csv'
      get 'find'
      get 'fetch_section_resources'
      get 'fetch_active_menu_products'
    end
    resources :commission_rules
    resources :beneficiaries
  end
  resources :commission_rules do
    collection do
      post "quick_update"
    end
  end
  resources :resource_types
  resources :beneficiaries

  resources :customer_queues

  resources :lots, only: [:show] do
    collection do
      put "delete_lot_sale_rule"
      put "lot_quick_update"
    end
  end
  resources :delivery_reports, only: [:index] do 
    collection do 
      get "slot_specific_delivery_reports"
      get "delivery_boys_report"
    end
  end
  mount Rscratch::Engine => '/rscratch'
  resources :reprint_details,only: [:index]

  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do
      resources :doc_types
      resources :check_informations, only: [:index, :update, :show] do
        collection do 
        end  
      end 
      resources :financial_accounts
      resources :customer_product_wishlists do
        collection do
          post 'remove_product'
        end  
      end  
      resources :financial_accounts_transactions do
        collection do 
          post 'debit'
        end  
      end  
      resources :proformas
      resources :boxings, only: [:create, :update, :show] do
        collection do
          post 'search_by_barcode'
          post 'create_box'
          post 'create_box_item'
          post 'remove_box_item'
        end
      end
      resources :reason_codes, only: [:index] do
        collection do
          get 'master_models'
          get 'model_actions'
        end
      end
      resources :warehouses do 
        collection do 
          post 'put_product'
          post 'pick_product'
          get 'product_bins'
          get 'bin_product_quantity'
        end
      end
      resources :packages do 
        collection do 
          get 'required_product_fields'
          post 'add_product'
          post 'package_creation'
          post 'edit_package_name'
          post 'create_package_unit'
          post 'edit_package_unit'
          post 'add_package_unit_product'
          post 'add_product_composition'
          get 'package_details'
          post 'add_package_component'
          get 'package_component_details'
          post 'remove_package_unit'
          post 'remove_package_unit_product'
        end
      end
      resources :cost_categories
      resources :beneficiaries, only: [:index]
      resources :labels, only: [:index]
      resources :return_items, only: [:index, :update]
      resources :questions, only: [:index, :show]
      resources :return_item_reports
      resources :user_login_logouts
      resources :delivery_addresses
      resources :bill_reprints, only: [:index, :create, :show]
      resources :user_work_statuses, only: [:create] do
        collection do
          get "work_statuses"
        end  
      end  
      resources :customer_communications, only: [:create] do
        collection do
          get "communications"
        end
      end
      resources :customer_tags, only: [:index,:create]
      resources :customer_notes, only: [:index,:create] do 
        collection do 
          get "notes"
        end
      end
      resources :resource_product_stocks, only: [:create]
      resources :visiting_histories, only: [:create, :index, :show]
      resources :item_preferences, only: [:index]
      resources :bill_destinations, only: [:index]
      resources :upi_merchants, only: [:index]
      resources :delivery_boys do
        collection do
          post "sign_in"
        end
      end
      resources :quotations
      resources :configurations, only: [:index]
      resources :days, only: [:index] do
        collection do
          get "menu_mapping"
        end  
      end
      resources :offers , only: [:index] do
        collection do
          post 'get_offers'
        end
      end 
      resources :units, only: [:index, :show] do
        collection do
          get "get_units"
          get "units_sales_persons"
        end  
      end  
      resources :sections, only: [:show] do
        collection do
          get 'section_tax_groups'
        end
      end
      resources :menu_cards, only: [:index, :show] do
        collection do
          get 'mp_sale_rules'
          get 'download_menu_cards'
        end
        member do
          get "product/:product_id", to: "menu_cards#product"
        end
      end
      resources :boutique_capillaries do
        collection do

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout "material"
  
  before_filter :set_module_details  
  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
    @account = request.subdomain
    @report_data = @report.generate_report
    @report_agg_data = @report.aggregation_attributes if @report.aggregation_functions.present?
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
      format.pdf { render :layout => false } # Add this line
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report_folder = ReportFolder.find(params[:report_folder_id]);
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    @report_folder = ReportFolder.find(params[:report_folder_id])
    @report = @report_folder.reports.build(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to customize_step_report_folder_report_path(@report_folder,@report,1), notice: 'Report template was successfully created.' }
        #format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        #format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /reports/1/edit
  def customize
    
    @form_data = params
    @data_tables = Report.get_model_info(params[:report_folder_id])
    @report_folder = ReportFolder.find(params[:report_folder_id])
    @report = Report.find(params[:id])
    if request.get? || params[:step_id]=='1'
      @partial_view  = "model_listing"
    end
    if request.post?
      if params[:step_id]=='2' 
        @partial_view = 'criteria'
      elsif params[:step_id]=='3'
        @partial_view = 'extra_criteria'
        @report.report_selectors = params[:report_selectors].join(",")
        @report.report_criteria = params[:report][:report_criteria]
        @report.save
      elsif params[:step_id]=='4'
        @form_data[:report_selectors] = @report.report_selectors.split(',')
        @partial_view = 'final'
        if params[:report] && params[:report][:aggregation_functions]
          @report.aggregation_functions = params[:report][:aggregation_functions].join(",")
          @report.save
        end
      elsif params[:step_id]=='5'
        @report.group_attribute = ''
        @report.order_attribute = ''
        if params[:report] && params[:report][:group_attribute]
          @report.group_attribute = params[:report][:group_attribute] 
        end
        if params[:report] && params[:report][:order_attribute]
          @report.order_attribute = params[:report][:order_attribute] 
        end
        respond_to do |format|
          if @report.save
            format.html { redirect_to report_folders_path, notice: 'Report was successfully created.' }
          end
        end
      else
        redirect_to customize_step_report_folder_report_path(@report_folder,@report,1)
      end
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report successfully Deleted.' }
      format.json { head :no_content }
    end
  end
 
  def get_bill_wise_report
    if params[:device_id].present?
      @array = Report.bill_wise_report(params)
    end
    rescue Exception => @error
  end

  def get_category_wise_report
    @unit = Unit.find(params[:unit_id])
    @unit_detail_options = @unit.unit_detail.options
    if params[:from_date].present?
      _from_datetime = params[:from_date].to_date.beginning_of_day+@unit_detail_options[:day_closing_time].to_i.hours
      _from_datetime ||= params[:from_date].to_date.beginning_of_day
      _to_datetime = params[:to_date].to_date.end_of_day+@unit_detail_options[:day_closing_time].to_i.hours
      _to_datetime ||= params[:to_date].to_date.end_of_day
    else
      _from_datetime = params[:date].to_date.beginning_of_day+@unit_detail_options[:day_closing_time].to_i.hours
      _from_datetime ||= params[:date].to_date.beginning_of_day
      _to_datetime = params[:date].to_date.end_of_day+@unit_detail_options[:day_closing_time].to_i.hours
      _to_datetime ||= params[:date].to_date.end_of_day
    end
    if params[:device_id].present? && params[:unit_id].present?
      @category_sales = Report.category_wise_report(params)
      @settlement_data = Bill.get_unit_settlement_data(params[:unit_id],_from_datetime,_to_datetime)
    end
    rescue Exception => @error
  end

  private

  def set_module_details
    @module_id = "reports"
    @module_title = "Reports"
  end    
end

app/helpers/reports_helper.rb
module ReportsHelper
  def get_data_type(selector)
    _model_class   =   selector.split('.').first.classify.constantize
    _col_name      =   selector.split('.').second
    _model_class.columns_hash[_col_name].type.to_s
  end

  def get_cb_agg_name(agg_fn,field)
    "#{agg_fn}(#{field})"
  end

  def is_checked_agg_cb(agg_fn,field)
    (@report.aggregation_functions || '').include?get_cb_agg_name(agg_fn,field)
  end
  def check_field(model_name,field_name)
    return model_name.where('\'#{field_name}\' IS NOT NULL').select(field_name)
    # _attribute_validation = _model_name.where('\'#{_field_value}\' IS NOT NULL').select(_field_value)
  end
  def replace_string_char(value)
    return value.gsub( ',', '_' ).gsub('.','_').gsub('(','_Of_All_').gsub(')','')
  end
end

app/views/reports/_criteria.html.haml
= javascript_include_tag "/js/query-builder.min.js"
= javascript_include_tag "/js/query-builder-sql-support.js"


= form_for @report, method: "post", url: customize_step_report_folder_report_path(@report_folder,@report,3) do |f| 
  - _celrctor_collection = @form_data[:report_selectors]
  - @form_data[:report_selectors].each do |filter_col|
    %input{:type =>"hidden",:name=>"report_selectors[]",:value=>filter_col}
    %br

  = f.text_area :report_criteria, :rows=>2, :html=>{:style=>"overflow:auto"}  
  = f.submit "Next", :class=>"m-btn teal"
.col-md-12.col-lg-10.col-lg-offset-1
  #builder
  .btn-group
    %button.btn.btn-warning.reset Reset
    /%button.btn.btn-success.set Set rules
  .btn-group
    /%button.btn.btn-primary.parse-json JSON
    /%button.btn.btn-primary.parse-sql{"data-stmt" => "question_mark"} SQL (question mark)
    /%button.btn.btn-primary.parse-sql{"data-stmt" => "numbered"} SQL (numbered)
    %button.btn.btn-primary.parse-sql{"data-stmt" => "false"} SQL
    /%button.btn.btn-primary.parse-mongo MongoDB

    
- @filters = Array.new

- @form_data[:report_selectors].each do |filter_col|
  - data_type = get_data_type(filter_col)
  - unless data_type =="text"
    - data_type = "double" if data_type == "float"
    - id= label = filter_col
    - id= "date(#{filter_col})" if data_type == "datetime"
    
    - tmp         = Hash.new
    - tmp[:id]    = id
    - tmp[:label] = label
    - tmp[:type]  = data_type
    - @filters << tmp
- @filter_json = @filters.to_json

.row
  =# debug @filters.to_json
  = #debug (@filters)

:javascript
  // define filters
  var tmp_data = "#{j @filter_json}";
  tmp_data = JSON.parse(tmp_data);
  $('#builder').queryBuilder({
    sortable: true,
    
    onValidationError: function($target, err) {
        console.error(err, $target);
    },
    
    filters: tmp_data
  });
  
  $('.set').on('click', function() {
    $('#builder').queryBuilder('setRules', {
      condition: 'AND',
      rules: [{
        id: 'price',
        operator: 'between',
        value: [10.25, 15.52],
        flags: {
          no_delete: true,
          filter_readonly: true
        }
      }, {
        condition: 'OR',
        rules: [{
          id: 'category',
          operator: 'equal',
          value: 2
        }, {
          id: 'coord',
          operator: 'equal',
          value: 'B.3'
        }]
      }]
      
    });
  
    $('.parse-json').trigger('click');
  })
  //.trigger('click');
  
  // reset builder
  $('.reset').on('click', function() {
    $('#builder').queryBuilder('reset');
    $('#result').addClass('hide').find('pre').empty();
  });
  
  // get rules
  $('.parse-json').on('click', function() {
    $('#result').removeClass('hide')
      .find('pre').html(JSON.stringify(
        $('#builder').queryBuilder('getRules'),
        undefined, 2
      ));
  });
  
  $('.parse-sql').on('click', function() {
    var res = $('#builder').queryBuilder('getSQL', $(this).data('stmt'), false);
    $('#report_report_criteria').val(res.sql + (res.params ? '\n\n' + JSON.stringify(res.params, undefined, 2) : '')
      );
  });
  
  $('.parse-mongo').on('click', function() {
    $('#result').removeClass('hide')
      .find('pre').html(JSON.stringify(
        $('#builder').queryBuilder('getMongo'),
        undefined, 2
      ));
  });


= javascript_include_tag "http://mistic100.github.io/jQuery-QueryBuilder/dist/bootstrap-datepicker/js/bootstrap-datepicker.js"
%link{:href => "http://mistic100.github.io/jQuery-QueryBuilder/dist/bootstrap-datepicker/css/datepicker3.css", :rel => "stylesheet", :type => "text/css"}











  

app/views/reports/_extra_criteria.haml
- @filters = Array.new

- @form_data[:report_selectors].each do |filter_col|
  - data_type = get_data_type(filter_col)
  - if data_type == "integer" || data_type == "float"
    - tmp = Hash.new
    - tmp[:id]= filter_col
    - tmp[:label]= filter_col
    - tmp[:type] = data_type
    - @filters << tmp
    
- @filter_json = @filters.to_json

%table.newtable{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tbody
    %tr
      %th{:width => "35%"} Columns
      %th.aligncenter{:width => "10%"} Sum
      %th.aligncenter{:width => "10%"} Average
      %th.aligncenter{:width => "15%"} Lowest Value
      %th.aligncenter{:width => "20%"} Largest Value
  = form_for @report, method: "post", url: customize_step_report_folder_report_path(@report_folder,@report,4) do |f|
    - @filters.each do |row| 
      -# if row[:type] == "integer" || row[:type] == "float"
      %tr
        %td{:nowrap => ""}
          = row[:label].humanize
          =# debug row
        %td.aligncenter
          = f.check_box :aggregation_functions,  {:multiple => true ,:checked=>is_checked_agg_cb("SUM",row[:label]), id: "report_aggregation_functions_sum#{row[:id]}"}, get_cb_agg_name("SUM",row[:label]),nil
          %label{:for=>"report_aggregation_functions_sum#{row[:id]}"}
        %td.aligncenter
          = f.check_box :aggregation_functions,  {:multiple => true ,:checked=>is_checked_agg_cb("AVG",row[:label]), id: "report_aggregation_functions_avg#{row[:id]}"}, get_cb_agg_name("AVG",row[:label]),nil
          %label{:for=>"report_aggregation_functions_avg#{row[:id]}"}
        %td.aligncenter
          = f.check_box :aggregation_functions,  {:multiple => true ,:checked=>is_checked_agg_cb("MIN",row[:label]), id: "report_aggregation_functions_min#{row[:id]}"}, get_cb_agg_name("MIN",row[:label]),nil
          %label{:for=>"report_aggregation_functions_min#{row[:id]}"}
        %td.aligncenter
          = f.check_box :aggregation_functions,  {:multiple => true ,:checked=>is_checked_agg_cb("MAX",row[:label]), id: "report_aggregation_functions_max#{row[:id]}"}, get_cb_agg_name("MAX",row[:label]),nil
          %label{:for=>"report_aggregation_functions_max#{row[:id]}"}
    %tr
      %td  
        #cvbutton{:align => "center"}
        %br
          = f.submit "Reset", :type => "reset", :class=>"m-btn white grey-text"
          = f.submit "Next", :class=>"m-btn teal"
=# debug (@filters)

app/views/reports/_final.html.haml
- @filters = Array.new

- @form_data[:report_selectors].each do |filter_col|
  - data_type = get_data_type(filter_col)
  - unless data_type =="text"
    - tmp = Hash.new
    - tmp[:id]= filter_col
    - tmp[:label]= filter_col
    - tmp[:type] = data_type
    - @filters << tmp
  
- @filter_json = @filters.to_json

%table.newtable{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tbody
    %tr
      %th{:width => "35%"} Columns
      %th.aligncenter{:width => "10%"} Group By
      %th.aligncenter{:width => "10%"} Order By
  = form_for @report, method: "post", url: customize_step_report_folder_report_path(@report_folder,@report,5) do |f|
    - @filters.each do |row| 
      %tr
        %td{:nowrap => ""}= row[:label].humanize
        %td.aligncenter
          -label = row[:type] == "datetime" ? "date(#{row[:label]})" : row[:label]
          = f.radio_button :group_attribute, label, id: "report_group_attribute_#{row[:id]}", class: "with-gap"
          %label{:for=>"report_group_attribute_#{row[:id]}"}
        %td.aligncenter
          = f.radio_button :order_attribute, label, id: "report_order_attribute_#{row[:id]}", class: "with-gap"
          %label{:for=>"report_order_attribute_#{row[:id]}"}
    %tr
      %td  
        #cvbutton{:align => "center"}
        %br
          = f.submit "Reset", :type => "reset", :class=>"m-btn white grey-text"
          = f.submit "Next", :class=>"m-btn teal"

app/views/reports/_form.html.haml
= form_for [@report_folder,@report],:html => {:class => "form-horizontal"} do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    .form-group
      = f.label :name,{:class => "col-md-2 control-label"},{:for => "textinput"}
      .col-md-4
        = f.text_field :name,{:class => "form-control input-md" ,:placeholder => "Report Name" ,:required => true}
    .form-group
      %label.col-md-2.control-label{:for => "singlebutton"}
      .col-md-4
        = f.submit 'Save & Customize',{:class => "singlebutton btn btn-success"}

app/views/reports/_model_listing.html.haml
= form_for @report, method: "post", url: customize_step_report_folder_report_path(@report_folder,@report,2), :html => { :id => "check_box_validate" } do |f|
  .col-lg-10
    - @data_tables.each do |data_table|
      %ul.collection.with-header
        %li.collection-header
          %h5  
            - _model_name = data_table.first.to_s.classify.constantize
            = data_table.first.humanize        
        %li.collection-item
          - data_table.second.each do |rel_tbl_column|
            - _field_value = "#{data_table.first}.#{rel_tbl_column[:name]}"
            - _attribute_validation = check_field(_model_name,_field_value)
            - if @report_folder[:attributes_accessible].include?_field_value
              .col-lg-4
                %input{:type =>"checkbox",:name=>"report_selectors[]",:class=>"check",:id =>"select_#{data_table.first}_#{rel_tbl_column[:name]}",:value=>_field_value,:checked=>((@report.report_selectors || '').include?_field_value)}
                %label{:for=>"select_#{data_table.first}_#{rel_tbl_column[:name]}"}= rel_tbl_column[:name].humanize 
          .clearfix

  .col-lg-2          
    = f.submit "Next", :class=>"m-btn teal"

                

             

app/views/reports/customize.html.haml
.page-header
  - if notice.nil? == false
    #notice.alert.alert-info
      %span.fa-stack.fa-lg
        %i.fa.fa-circle.fa-stack-2x
        %i.fa.fa-info.fa-stack-1x.fa-inverse
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = notice
  %h2
    %i.fa.fa-tags
    Report Customization
.page-container  
  = render @partial_view
     

app/views/reports/index.html.haml
%h1 Listing reports

%table
  %tr
    %th Name
    %th Report folder
    %th
    %th
    %th

  - @reports.each do |report|
    %tr
      %td= report.name
      %td= report.report_folder
      %td= link_to 'Show', report
      %td= link_to 'Edit', edit_report_path(report)
      %td= link_to 'Destroy', report, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Report template', new_report_folder_report_path

app/views/reports/new.html.haml
.page-header
  - if notice.nil? == false
    #notice.alert.alert-info
      %span.fa-stack.fa-lg
        %i.fa.fa-circle.fa-stack-2x
        %i.fa.fa-info.fa-stack-1x.fa-inverse
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = notice
  %h2
    %i.fa.fa-tags
    New Report
    %small Report Creation
.page-container  
  = render 'form'
  = link_to 'Back', report_folders_path 

app/views/reports/show.html.haml
.page-header
  - if notice.nil? == false
    #notice.alert.alert-info
      %span.fa-stack.fa-lg
        %i.fa.fa-circle.fa-stack-2x
        %i.fa.fa-info.fa-stack-1x.fa-inverse
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = notice
  %h2
    %i.fa.fa-tags
    #{@report.report_folder.name}
    
    %small #{@report.name}
.page-container  
  - if @report_data.first.present?
    - attr_names = @report_data.first.attribute_names
    %table.table.table-stripped.table-hover
      %thead
        %tr
          - attr_names.each do |attr_name|
            %th= attr_name.titleize
      %tbody
        - @report_data.each do |entry|

          %tr
            - attr_names.each do |key|

              %td= entry[key]
  - else
    No Data Found. 
  %hr            
  - if @report_grouped_data.present?          
    - attr_names = @report_grouped_data.first.attribute_names
    %table.table.table-stripped.table-hover
      %thead
        %tr
          - attr_names.each do |attr_name|
            %th= attr_name.titleize
      %tbody
        - @report_grouped_data.each do |entry|

          %tr
            - attr_names.each do |key|

              %td= entry[key]          
  - if @report_agg_data.present?
    - @report_agg_data.each do |row|
      - _value = row['label'][0..2].downcase
      %table.table.table-stripped.table-hover
        %thead
          %tr
            %th= replace_string_char(row['label']).titleize
            
            %th.align-right{:width => "20%"}= row['values'][0][_value].to_f.round
  
  - if @report_data.first.present? || @report_grouped_data.present?   
    / %a.btn.btn-block.btn-social.btn-danger{:href=> "#{report_folder_report_path}.pdf", :target => '_blank'}
    /   %i.fa.fa-calculator
    /   Download Report
    %a{:href => "#{report_folders_path}", :class => 'm-btn white grey-text text-darken-2'}
      %i.icon-backward
      Back 
  - else
    %a{:href => "#{report_folders_path}", :class => 'm-btn white grey-text text-darken-2'}
      Back    